# Generated by Django 5.0.4 on 2024-05-23 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_number', models.CharField(max_length=100, verbose_name='номер релиза')),
                ('release_title', models.CharField(max_length=100, verbose_name='название релиза')),
                ('activated', models.BooleanField(default=True, verbose_name='активен')),
                ('blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='releases', to='blogs.blog', verbose_name='блог')),
            ],
            options={
                'verbose_name': 'Релиз',
                'verbose_name_plural': 'Релизы',
            },
        ),
    ]
