# Generated by Django 5.0.4 on 2024-05-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_release_release_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='release_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='номер релиза'),
        ),
        migrations.AlterField(
            model_name='release',
            name='release_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='название релиза'),
        ),
    ]
