# Generated by Django 4.2.2 on 2024-06-07 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_blog_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'permissions': [('can_edit_description', 'Can edit description'), ('can_edit_author', 'Can edit author'), ('can_cancel_is_published', 'Can cancel publish')], 'verbose_name': 'блог', 'verbose_name_plural': 'блоги'},
        ),
    ]
