# Generated by Django 5.0.4 on 2024-05-13 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/photo/', verbose_name='Изображение'),
        ),
    ]
